kind: pipeline
type: docker
volumes:
- name: temp
  temp: {}
- name: docker
  host:
    path: /var/run/docker.sock
steps:
- name: master_build
  image: registry-vpc.cn-hangzhou.aliyuncs.com/profzone/golang-onbuild:1.14
  commands:
  - eden ci run build
  environment:
    GOENV: PROD
  when:
    branch:
      include:
      - master
      exclude: []
  volumes:
  - name: temp
    path: /go
- name: master_ship
  image: registry-vpc.cn-hangzhou.aliyuncs.com/profzone/golang-onship:1.14
  commands:
  - eden ci ship --push
  environment:
    GOENV: PROD
  when:
    branch:
      include:
      - master
      exclude: []
  volumes:
  - name: temp
    path: /go
  - name: docker
    path: /var/run/docker.sock
- name: master_deploy
  image: registry-vpc.cn-hangzhou.aliyuncs.com/profzone/golang-ondeploy:1.0
  commands:
  - eden ci deploy --env=PROD
  environment:
    GOENV: PROD
  when:
    branch:
      include:
      - master
      exclude: []
  volumes:
  - name: temp
    path: /go
