name: srv-w2w
group: services
owner: eden-w2w
version: 0.0.0
description: w2w
program_language: golang
workflow:
  extends: feature-pr
scripts:
  build:
  - go build -v -o ./build/$PROJECT_NAME -ldflags "-X github.com/eden-framework/apollo.Branch=$DRONE_BRANCH.json"
    ./cmd
  - eden generate openapi
  test: go test ./cmd
